ch46:
	gcc -g -Wall ch46.c -o ch46

ch47:
	gcc -g -Wall ch47.c -o ch47

ch48:
	gcc -g -Wall ch48.c -o ch48

ch49:
	gcc -g -Wall ch49.c -o ch49

ch50:
	gcc -g -Wall ch50.c -o ch50

clean:
	$(RM) ch46 ch47 ch48 ch49 ch50
